openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in HTML.
  version: 0.1.9
servers:
  - url: http://localhost:3000/api/artists
    description: Optional server description, e.g. Main (production) server
 
paths:
  /:
    get:
      summary: Returns a list of all the artists artists.
      description: get all artists list
      responses:
        "200": # status code
          description: A JSON array of artist infromation
          content:
            application/json:
              schema:
                type: array
                 :
                  id:
                    type: integer
                    example: 4
                  firstName:
                    type: string
                    example: Jessica 
                  lastName:
                    type: string
                    example: Parker 
                  email:
                    type: string
                    example: ines@gmail.com 
                  password:
                    type: string
                    example: 123@!
                  telNumber:
                    type: integer
                    example: 22345761
                  accept:
                    type: boolean
                    example: false
                  banned:
                    type: boolean
                    example: false
        "404":
        default:
          description: Unexpected error
         
          
  /{id}:
    put:
      summary: update the state banned of the artist 
      description:  returns the updated artist.
    
      responses:
        "200": # status code
          description: Object with the artist infromation
          consumes:
            - application/json
          parameters: 
            in: path
              name: id
              description: artist id that needs to be banned,
              type: string"
            in: body
              description: artist to ban or to ban or to accept .
              name: artist
              schema:
                type: object
                required:
            
                properties:
                  accept:
                    type: boolean
                      example: false
                  banned:
                    type: boolean
                        example: false                    
        "404":
        default:
          description: Unexpected error
  #            email: type.STRING,
  #     password: type.STRING,
  #     description: type.STRING,
  #     imageUrl: type.STRING,
  #     telNumber: type.INTEGER,
  #     accept: {
  #       type: type.BOOLEAN,
  #       defaultValue: false,
  #     },
  #     banned: {
  #       type: type.BOOLEAN,
  #       defaultValue: false,
  #     },
  #   },
  #   { timestamps: false }
  # );